### ISSUE TITLE
add units to query results as an options

### ISSUE THREAD

**Issue by enryH** [CorrelAid/datenguide-python#68]
* Datenguide Python version: dev
* Python version: 3.8.1

### Description
If a field is added, enum values are "None" (=Gesamt), which is not intuitive. This can be avoided by calling `add_args`, see [`README.rst`](https://github.com/CorrelAid/datenguide-python/blob/4cfbb21a7538c7dcaf54c86b9b3528c93f84ea15/README.rst#setup-query) point 5 of Section Query Setup. Proposal is to integrate this into the main function executing the query as default: [`Query.results`](https://github.com/CorrelAid/datenguide-python/blob/c60e42ceb2aadc75d156e48994bd2c965c1d37ec/datenguidepy/query_builder.py#L610)

**Comment by KonradUdoHannes** [comment]
A minimal example of the type of query this relates too would be
```python
q = Query.region("01")
stat = q.add_field("TIE003")
stat.add_args({'TIEA05' : 'ALL'})
stat.add_field('TIEA05')
q.results()
```
In this case the enum values TIEA05 (type of animal) are added too the query. This enters the query logically in two places. The `.add_field` method adds this enum value as a column to be displayed, whereas the `.add_args` method modifies the type of information the query returns (which and how many rows).

I think several things should be considered regarding this issue. First of all there is not guaranteed link between the name of the argument and the name of the field, which are currently only the same (TIEA05) by convention in our specific API. This convention will probably stay in place, but is not necessarily  guaranteed for all statistics for the future. As such error handling/error messages that make a failure due to a name mismatch here more transparent would probably be good.

From a data application point of view I'm not sure what a sensible default is for this issue. If `.add_args` is set internally whenever an enum is added to `.add_field`, the effect fo the use is that displaying a column or not, has an effect on the number of rows that are returned to the user, which I would say is not expected intuitively most of the time. At the same time `None` (Total/Gesamt) is the only sensible default value in case the enum column is not displayed.
It might me sensible to think about defaults the other way around and add the field by default when the argument is set. I don't think creating additional columns when the amount of returned data changes is not as confusing as it is the other way around, and it definitely makes sense when the argument is set to "ALL", because otherwise different values for the same year cannot be distinguished.

**Comment by enryH** [comment]
```python
from datenguidepy import Query
q = Query.region("01")
stat = q.add_field("TIE003")
# stat.add_args({'TIEA05' : 'ALL'})
stat.add_field('TIEA05')
df = q.results()
```
So it's not about naming the aggregate "Gesamt"/Total?
```
   id                name  year TIEA05   TIE003                          TIE003_source_title_de TIE003_source_valid_from TIE003_source_periodicity TIE003_source_name TIE003_source_url
0  01  Schleswig-Holstein  2010   None   364240  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
1  01  Schleswig-Holstein  2010   None  1137172  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
2  01  Schleswig-Holstein  2010   None  1620161  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
3  01  Schleswig-Holstein  2010   None   281728  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
4  01  Schleswig-Holstein  2010   None   116356  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
5  01  Schleswig-Holstein  2016   None   396358  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
6  01  Schleswig-Holstein  2016   None    94106  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
7  01  Schleswig-Holstein  2016   None  1095984  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
8  01  Schleswig-Holstein  2016   None  1461628  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
9  01  Schleswig-Holstein  2016   None   205685  Agrarstrukturerhebung / Landwirtschaftszählung      2010-01-01T00:00:00             ZEHNJAEHRLICH              41141              None
```

**Comment by enryH** [comment]
@KonradUdoHannes  Could you post your example where you have `'units'`-key in the meta-data. I don't get it, also not using `q.results(verbose_enums=True, verbose_statistics=True)`

```python
q.meta_data()
>>>{'statistics': {'TIE003': 'Tiere'},
 'enums': {'TIEA05': {'AGRVART01': 'Rinder insgesamt',
   'AGRVART11': 'Milchkühe',
   'TIERART03A': 'sonstige Kühe',
   'TIERART20412M': 'Männliche Rinder 1 bis unter 2 Jahren',
   'TIERART20412W': 'Weibl. Rinder 1 bis unter 2 J. (nicht abgekalbt)',
   'TIERART20413M': 'Männliche Rinder 2 Jahre und älter',
   'TIERART20413W': 'Weibl. Rinder 2 J. und älter (nicht abgekalbt)',
   'TIERART204141M': 'Männliche Kälber bis einschl. 8 Monate',
   'TIERART204141RM': 'Männl. Jungrinder m. als 8 Mon. b. einschl. 1 Jahr',
   'TIERART204141RW': 'Weibl. Jungrinder m. als 8 Mon. b. einschl. 1 Jahr',
   'TIERART204141W': 'Weibliche Kälber bis einschl. 8 Monate',
   'GESAMT': 'Gesamt'}}}
```
I guess it's not present allways?

**Comment by KonradUdoHannes** [comment]
Currently the units are only present in the unit_meta_data feature branch. Unfortunately I forgot to mention it because I did not remember whether it was merged already or not. I think the original idea was to merge the feature branch once units are also available to the user.

**Comment by enryH** [comment]
Thanks. The `unit_meta_data` branch yields then
```python
q.meta_data()
>>>{
 'statistics': {'TIE003': 'Tiere'},
 'enums': {
   'TIEA05': {
     'AGRVART01': 'Rinder insgesamt',
     'AGRVART11': 'Milchkühe',
     'TIERART03A': 'sonstige Kühe',
     'TIERART20412M': 'Männliche Rinder 1 bis unter 2 Jahren',
     'TIERART20412W': 'Weibl. Rinder 1 bis unter 2 J. (nicht abgekalbt)',
     'TIERART20413M': 'Männliche Rinder 2 Jahre und älter',
     'TIERART20413W': 'Weibl. Rinder 2 J. und älter (nicht abgekalbt)',
     'TIERART204141M': 'Männliche Kälber bis einschl. 8 Monate',
     'TIERART204141RM': 'Männl. Jungrinder m. als 8 Mon. b. einschl. 1 Jahr',
     'TIERART204141RW': 'Weibl. Jungrinder m. als 8 Mon. b. einschl. 1 Jahr',
     'TIERART204141W': 'Weibliche Kälber bis einschl. 8 Monate',
     'GESAMT': 'Gesamt'}},
 'units': {'TIE003': 'Anzahl'}}
```

> Konrad: In GraphQL enums are custom data types with a discrete number of predefined possible values. For example the enum data type GES (gender) has the enum values GESMand GESWfor male and female. In the "cube wording" from the original GENESIS database enums are called dimensions and enum values are called members, which might be relevant to know when browsing the new meta data endpoints.

Does this mean `TIE003` has no `enums`, i.e. more specific variables/dimensions?

**Comment by KonradUdoHannes** [comment]
No the statistic `TIE003` has the dimension `TIEA05`, which has the listed possible values. The units only refer to the statistic itself and are the same for all dimension/enum values. I would say this makes sense to have comparable numbers.
In case one queries a meta data of a query with a single statistic all enums will always belong to that statistic. In case you design a query containing several statistics the method `.meta_data` will list all enums contained in all (in the sense of union) statistics of the query, which means it won't be immediately obvious which enum belongs to which statistic.
